DROP TABLE fractals;
CREATE TABLE fractals (
  id INTEGER PRIMARY KEY NOT NULL,
  created_time INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
  json TEXT NOT NULL,
  consumed BOOLEAN NOT NULL DEFAULT 0,
  rank INTEGER UNIQUE
)
